import BSCAveraging.CoreDeriv

/-! # Regime 1 of (iii)'s core: the polynomial certificate

`NOTES.md` §7f¹².  After the log-free reduction (`F_pos_of_exp_bound`) regime 1
becomes the algebraic inequality

```
3 s (a+s³)³  <  3a²(a+s³)² + 2a³s²(a+s³) + a⁴s⁴ ,   a = θ cosh θ, s = sinh θ.
```

Replacing `sinh`, `cosh` by their Taylor polynomials with the `Real.exp_bound`
remainder turns it into positivity of an explicit rational polynomial `P` of
degree 60, vanishing to order 8 with leading coefficient `4/15`.  Its quotient
`Qpoly = P/θ⁸` has 53 terms, and `q₀ = 4/15 = 0.2667` dominates the entire
negative mass `0.0191` at `θ = 0.45` — so plain coefficient domination suffices,
with no Bernstein certificate.

Generated by `numerics/p0_regime1.py`. -/

set_option maxHeartbeats 1000000

namespace BSCAveraging.Core

/-- `P/θ⁸`, where `P` is the polynomial lower bound for the cleared core. -/
noncomputable def Qpoly (θ : ℝ) : ℝ :=
    (4/15 : ℝ) * θ ^ 0
    + (-7/1440 : ℝ) * θ ^ 1
    + (979/1440 : ℝ) * θ ^ 2
    + (-175/1728 : ℝ) * θ ^ 3
    + (6821/8640 : ℝ) * θ ^ 4
    + (-32473/103680 : ℝ) * θ ^ 5
    + (193033/518400 : ℝ) * θ ^ 6
    + (-864913/2073600 : ℝ) * θ ^ 7
    + (160607/18662400 : ℝ) * θ ^ 8
    + (-11751061/37324800 : ℝ) * θ ^ 9
    + (-38963/460800 : ℝ) * θ ^ 10
    + (-175332311/1119744000 : ℝ) * θ ^ 11
    + (-12065819/223948800 : ℝ) * θ ^ 12
    + (-1497856157/26873856000 : ℝ) * θ ^ 13
    + (-7929114901/403107840000 : ℝ) * θ ^ 14
    + (-2004265081/134369280000 : ℝ) * θ ^ 15
    + (-169937473/33592320000 : ℝ) * θ ^ 16
    + (-30003769621/9674588160000 : ℝ) * θ ^ 17
    + (-12793203631/12899450880000 : ℝ) * θ ^ 18
    + (-3980450537/7739670528000 : ℝ) * θ ^ 19
    + (-54271275097/348285173760000 : ℝ) * θ ^ 20
    + (-30406587113/435356467200000 : ℝ) * θ ^ 21
    + (-26726751317/1306069401600000 : ℝ) * θ ^ 22
    + (-83653888577/10448555212800000 : ℝ) * θ ^ 23
    + (-12959755007/5572562780160000 : ℝ) * θ ^ 24
    + (-6018199173553/7522959753216000000 : ℝ) * θ ^ 25
    + (-389698614839/1671768834048000000 : ℝ) * θ ^ 26
    + (-1074169941229/15045919506432000000 : ℝ) * θ ^ 27
    + (-3096965538431/150459195064320000000 : ℝ) * θ ^ 28
    + (-5171623144429/902755170385920000000 : ℝ) * θ ^ 29
    + (-17148932084263/10833062044631040000000 : ℝ) * θ ^ 30
    + (-4435650265963/10833062044631040000000 : ℝ) * θ ^ 31
    + (-342412563533/3249918613389312000000 : ℝ) * θ ^ 32
    + (-185590303339/7222041363087360000000 : ℝ) * θ ^ 33
    + (-1979251412051/324991861338931200000000 : ℝ) * θ ^ 34
    + (-7275047233769/5199869781422899200000000 : ℝ) * θ ^ 35
    + (-2870059986269/9359765606561218560000000 : ℝ) * θ ^ 36
    + (-2038971517583/31199218688537395200000000 : ℝ) * θ ^ 37
    + (-746540537317/56158593639367311360000000 : ℝ) * θ ^ 38
    + (-2907406931821/1123171872787346227200000000 : ℝ) * θ ^ 39
    + (-1631330049263/3369515618362038681600000000 : ℝ) * θ ^ 40
    + (-385058500043/4492687491149384908800000000 : ℝ) * θ ^ 41
    + (-3651096016289/252713671377152901120000000000 : ℝ) * θ ^ 42
    + (-699534344131/303256405652583481344000000000 : ℝ) * θ ^ 43
    + (-52046501647/151628202826291740672000000000 : ℝ) * θ ^ 44
    + (-268126187/5615859363936731136000000000 : ℝ) * θ ^ 45
    + (-620564861/101085468550861160448000000000 : ℝ) * θ ^ 46
    + (-309309456463/436689224139720213135360000000000 : ℝ) * θ ^ 47
    + (-117766649/1617367496813778567168000000000 : ℝ) * θ ^ 48
    + (-3403703219/524027068967664255762432000000000 : ℝ) * θ ^ 49
    + (-5764801/12938939974510228537344000000000 : ℝ) * θ ^ 50
    + (-40353607/2096108275870657023049728000000000 : ℝ) * θ ^ 51
    + (-282475249/754598979313436528297902080000000000 : ℝ) * θ ^ 52

/-- **`Qpoly > 0` on `[0, 0.45]`**: the constant term `4/15` dominates the whole
negative mass, which is at most `0.0191`. -/
theorem Qpoly_pos {θ : ℝ} (h0 : 0 ≤ θ) (h1 : θ ≤ 45/100) : 0 < Qpoly θ := by
  have trm1 : (-7/3200 : ℝ) ≤ (-7/1440 : ℝ) * θ ^ 1 := by
    have hp : θ ^ 1 ≤ (45/100:ℝ) ^ 1 := pow_le_pow_left₀ h0 h1 1
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-7/1440 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm2 : (0:ℝ) ≤ (979/1440 : ℝ) * θ ^ 2 := by positivity
  have trm3 : (-189/20480 : ℝ) ≤ (-175/1728 : ℝ) * θ ^ 3 := by
    have hp : θ ^ 3 ≤ (45/100:ℝ) ^ 3 := pow_le_pow_left₀ h0 h1 3
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-175/1728 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm4 : (0:ℝ) ≤ (6821/8640 : ℝ) * θ ^ 4 := by positivity
  have trm5 : (-23672817/4096000000 : ℝ) ≤ (-32473/103680 : ℝ) * θ ^ 5 := by
    have hp : θ ^ 5 ≤ (45/100:ℝ) ^ 5 := pow_le_pow_left₀ h0 h1 5
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-32473/103680 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm6 : (0:ℝ) ≤ (193033/518400 : ℝ) * θ ^ 6 := by positivity
  have trm7 : (-51072247737/32768000000000 : ℝ) ≤ (-864913/2073600 : ℝ) * θ ^ 7 := by
    have hp : θ ^ 7 ≤ (45/100:ℝ) ^ 7 := pow_le_pow_left₀ h0 h1 7
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-864913/2073600 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm8 : (0:ℝ) ≤ (160607/18662400 : ℝ) * θ ^ 8 := by positivity
  have trm9 : (-6244995608901/26214400000000000 : ℝ) ≤ (-11751061/37324800 : ℝ) * θ ^ 9 := by
    have hp : θ ^ 9 ≤ (45/100:ℝ) ^ 9 := pow_le_pow_left₀ h0 h1 9
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-11751061/37324800 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm10 : (-15095064512907/524288000000000000 : ℝ) ≤ (-38963/460800 : ℝ) * θ ^ 10 := by
    have hp : θ ^ 10 ≤ (45/100:ℝ) ^ 10 := pow_le_pow_left₀ h0 h1 10
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-38963/460800 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm11 : (-2515827024634077/104857600000000000000 : ℝ) ≤ (-175332311/1119744000 : ℝ) * θ ^ 11 := by
    have hp : θ ^ 11 ≤ (45/100:ℝ) ^ 11 := pow_le_pow_left₀ h0 h1 11
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-175332311/1119744000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm12 : (-1558181832388497/419430400000000000000 : ℝ) ≤ (-12065819/223948800 : ℝ) * θ ^ 12 := by
    have hp : θ ^ 12 ≤ (45/100:ℝ) ^ 12 := pow_le_pow_left₀ h0 h1 12
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-12065819/223948800 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm13 : (-580300164796600773/335544320000000000000000 : ℝ) ≤ (-1497856157/26873856000 : ℝ) * θ ^ 13 := by
    have hp : θ ^ 13 ≤ (45/100:ℝ) ^ 13 := pow_le_pow_left₀ h0 h1 13
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-1497856157/26873856000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm14 : (-9215704716847819767/33554432000000000000000000 : ℝ) ≤ (-7929114901/403107840000 : ℝ) * θ ^ 14 := by
    have hp : θ ^ 14 ≤ (45/100:ℝ) ^ 14 := pow_le_pow_left₀ h0 h1 14
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-7929114901/403107840000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm15 : (-62895961979098213329/671088640000000000000000000 : ℝ) ≤ (-2004265081/134369280000 : ℝ) * θ ^ 15 := by
    have hp : θ ^ 15 ≤ (45/100:ℝ) ^ 15 := pow_le_pow_left₀ h0 h1 15
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-2004265081/134369280000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm16 : (-47995361730142452513/3355443200000000000000000000 : ℝ) ≤ (-169937473/33592320000 : ℝ) * θ ^ 16 := by
    have hp : θ ^ 16 ≤ (45/100:ℝ) ^ 16 := pow_le_pow_left₀ h0 h1 16
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-169937473/33592320000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm17 : (-8473950746741739043701/2147483648000000000000000000000 : ℝ) ≤ (-30003769621/9674588160000 : ℝ) * θ ^ 17 := by
    have hp : θ ^ 17 ≤ (45/100:ℝ) ^ 17 := pow_le_pow_left₀ h0 h1 17
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-30003769621/9674588160000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm18 : (-97555821433480156387797/171798691840000000000000000000000 : ℝ) ≤ (-12793203631/12899450880000 : ℝ) * θ ^ 18 := by
    have hp : θ ^ 18 ≤ (45/100:ℝ) ^ 18 := pow_le_pow_left₀ h0 h1 18
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-12793203631/12899450880000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm19 : (-91059940812187060764057/687194767360000000000000000000000 : ℝ) ≤ (-3980450537/7739670528000 : ℝ) * θ ^ 19 := by
    have hp : θ ^ 19 ≤ (45/100:ℝ) ^ 19 := pow_le_pow_left₀ h0 h1 19
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-3980450537/7739670528000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm20 : (-1241552696660162413406217/68719476736000000000000000000000000 : ℝ) ≤ (-54271275097/348285173760000 : ℝ) * θ ^ 20 := by
    have hp : θ ^ 20 ≤ (45/100:ℝ) ^ 20 := pow_le_pow_left₀ h0 h1 20
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-54271275097/348285173760000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm21 : (-6260446643830134979658337/1717986918400000000000000000000000000 : ℝ) ≤ (-30406587113/435356467200000 : ℝ) * θ ^ 21 := by
    have hp : θ ^ 21 ≤ (45/100:ℝ) ^ 21 := pow_le_pow_left₀ h0 h1 21
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-30406587113/435356467200000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm22 : (-16508403257607843388208199/34359738368000000000000000000000000000 : ℝ) ≤ (-26726751317/1306069401600000 : ℝ) * θ ^ 22 := by
    have hp : θ ^ 22 ≤ (45/100:ℝ) ^ 22 := pow_le_pow_left₀ h0 h1 22
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-26726751317/1306069401600000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm23 : (-465037033227430213725960771/5497558138880000000000000000000000000000 : ℝ) ≤ (-83653888577/10448555212800000 : ℝ) * θ ^ 23 := by
    have hp : θ ^ 23 ≤ (45/100:ℝ) ^ 23 := pow_le_pow_left₀ h0 h1 23
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-83653888577/10448555212800000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm24 : (-1945189701314123290454348847/175921860444160000000000000000000000000000 : ℝ) ≤ (-12959755007/5572562780160000 : ℝ) * θ ^ 24 := by
    have hp : θ ^ 24 ≤ (45/100:ℝ) ^ 24 := pow_le_pow_left₀ h0 h1 24
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-12959755007/5572562780160000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm25 : (-301099803366379684234389148971/175921860444160000000000000000000000000000000 : ℝ) ≤ (-6018199173553/7522959753216000000 : ℝ) * θ ^ 25 := by
    have hp : θ ^ 25 ≤ (45/100:ℝ) ^ 25 := pow_le_pow_left₀ h0 h1 25
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-6018199173553/7522959753216000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm26 : (-1579275129690146740331715026013/7036874417766400000000000000000000000000000000 : ℝ) ≤ (-389698614839/1671768834048000000 : ℝ) * θ ^ 26 := by
    have hp : θ ^ 26 ≤ (45/100:ℝ) ^ 26 := pow_le_pow_left₀ h0 h1 26
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-389698614839/1671768834048000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm27 : (-4353132930545674838645135812143/140737488355328000000000000000000000000000000000 : ℝ) ≤ (-1074169941229/15045919506432000000 : ℝ) * θ ^ 27 := by
    have hp : θ ^ 27 ≤ (45/100:ℝ) ^ 27 := pow_le_pow_left₀ h0 h1 27
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-1074169941229/15045919506432000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm28 : (-112955612863416636869010588753693/28147497671065600000000000000000000000000000000000 : ℝ) ≤ (-3096965538431/150459195064320000000 : ℝ) * θ ^ 28 := by
    have hp : θ ^ 28 ≤ (45/100:ℝ) ^ 28 := pow_le_pow_left₀ h0 h1 28
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-3096965538431/150459195064320000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm29 : (-565873776632554522944724735196661/1125899906842624000000000000000000000000000000000000 : ℝ) ≤ (-5171623144429/902755170385920000000 : ℝ) * θ ^ 29 := by
    have hp : θ ^ 29 ≤ (45/100:ℝ) ^ 29 := pow_le_pow_left₀ h0 h1 29
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-5171623144429/902755170385920000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm30 : (-5629256440035050359270022136083901/90071992547409920000000000000000000000000000000000000 : ℝ) ≤ (-17148932084263/10833062044631040000000 : ℝ) * θ ^ 30 := by
    have hp : θ ^ 30 ≤ (45/100:ℝ) ^ 30 := pow_le_pow_left₀ h0 h1 30
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-17148932084263/10833062044631040000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm31 : (-13104297942550075867765205942188209/1801439850948198400000000000000000000000000000000000000 : ℝ) ≤ (-4435650265963/10833062044631040000000 : ℝ) * θ ^ 31 := by
    have hp : θ ^ 31 ≤ (45/100:ℝ) ^ 31 := pow_le_pow_left₀ h0 h1 31
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-4435650265963/10833062044631040000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm32 : (-3034781361984559587392140840157157/3602879701896396800000000000000000000000000000000000000 : ℝ) ≤ (-342412563533/3249918613389312000000 : ℝ) * θ ^ 32 := by
    have hp : θ ^ 32 ≤ (45/100:ℝ) ^ 32 := pow_le_pow_left₀ h0 h1 32
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-342412563533/3249918613389312000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm33 : (-133234905302188610408742936888561411/1441151880758558720000000000000000000000000000000000000000 : ℝ) ≤ (-185590303339/7222041363087360000000 : ℝ) * θ ^ 33 := by
    have hp : θ ^ 33 ≤ (45/100:ℝ) ^ 33 := pow_le_pow_left₀ h0 h1 33
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-185590303339/7222041363087360000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm34 : (-1420900605847670654591655158868870699/144115188075855872000000000000000000000000000000000000000000 : ℝ) ≤ (-1979251412051/324991861338931200000000 : ℝ) * θ ^ 34 := by
    have hp : θ ^ 34 ≤ (45/100:ℝ) ^ 34 := pow_le_pow_left₀ h0 h1 34
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-1979251412051/324991861338931200000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm35 : (-47004675925373494066007293508418046329/46116860184273879040000000000000000000000000000000000000000000 : ℝ) ≤ (-7275047233769/5199869781422899200000000 : ℝ) * θ ^ 35 := by
    have hp : θ ^ 35 ≤ (45/100:ℝ) ^ 35 := pow_le_pow_left₀ h0 h1 35
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-7275047233769/5199869781422899200000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm36 : (-18543692598276790547362016536821398829/184467440737095516160000000000000000000000000000000000000000000 : ℝ) ≤ (-2870059986269/9359765606561218560000000 : ℝ) * θ ^ 36 := by
    have hp : θ ^ 36 ≤ (45/100:ℝ) ^ 36 := pow_le_pow_left₀ h0 h1 36
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-2870059986269/9359765606561218560000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm37 : (-355696972512422762374373244021941524581/36893488147419103232000000000000000000000000000000000000000000000 : ℝ) ≤ (-2038971517583/31199218688537395200000000 : ℝ) * θ ^ 37 := by
    have hp : θ ^ 37 ≤ (45/100:ℝ) ^ 37 := pow_le_pow_left₀ h0 h1 37
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-2038971517583/31199218688537395200000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm38 : (-130233407721275290271218888279903309719/147573952589676412928000000000000000000000000000000000000000000000 : ℝ) ≤ (-746540537317/56158593639367311360000000 : ℝ) * θ ^ 38 := by
    have hp : θ ^ 38 ≤ (45/100:ℝ) ^ 38 := pow_le_pow_left₀ h0 h1 38
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-746540537317/56158593639367311360000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm39 : (-4564753608047582835737729472168135029223/59029581035870565171200000000000000000000000000000000000000000000000 : ℝ) ≤ (-2907406931821/1123171872787346227200000000 : ℝ) * θ ^ 39 := by
    have hp : θ ^ 39 ≤ (45/100:ℝ) ^ 39 := pow_le_pow_left₀ h0 h1 39
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-2907406931821/1123171872787346227200000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm40 : (-7683774479713786598994419048719332531207/1180591620717411303424000000000000000000000000000000000000000000000000 : ℝ) ≤ (-1631330049263/3369515618362038681600000000 : ℝ) * θ ^ 40 := by
    have hp : θ ^ 40 ≤ (45/100:ℝ) ^ 40 := pow_le_pow_left₀ h0 h1 40
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-1631330049263/3369515618362038681600000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm41 : (-48969227461620474920229719273525757382929/94447329657392904273920000000000000000000000000000000000000000000000000 : ℝ) ≤ (-385058500043/4492687491149384908800000000 : ℝ) * θ ^ 41 := by
    have hp : θ ^ 41 ≤ (45/100:ℝ) ^ 41 := pow_le_pow_left₀ h0 h1 41
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-385058500043/4492687491149384908800000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm42 : (-464322567313555070793669260780340955233267/11805916207174113034240000000000000000000000000000000000000000000000000000 : ℝ) ≤ (-3651096016289/252713671377152901120000000000 : ℝ) * θ ^ 42 := by
    have hp : θ ^ 42 ≤ (45/100:ℝ) ^ 42 := pow_le_pow_left₀ h0 h1 42
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-3651096016289/252713671377152901120000000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm43 : (-266886639909061021058361962512373333039979/94447329657392904273920000000000000000000000000000000000000000000000000000 : ℝ) ≤ (-699534344131/303256405652583481344000000000 : ℝ) * θ ^ 43 := by
    have hp : θ ^ 43 ≤ (45/100:ℝ) ^ 43 := pow_le_pow_left₀ h0 h1 43
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-699534344131/303256405652583481344000000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm44 : (-178711230608131503054512804856741016545807/944473296573929042739200000000000000000000000000000000000000000000000000000 : ℝ) ≤ (-52046501647/151628202826291740672000000000 : ℝ) * θ ^ 44 := by
    have hp : θ ^ 44 ≤ (45/100:ℝ) ^ 44 := pow_le_pow_left₀ h0 h1 44
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-52046501647/151628202826291740672000000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm45 : (-223720513673965777110172833451071915675921/18889465931478580854784000000000000000000000000000000000000000000000000000000 : ℝ) ≤ (-268126187/5615859363936731136000000000 : ℝ) * θ ^ 45 := by
    have hp : θ ^ 45 ≤ (45/100:ℝ) ^ 45 := pow_le_pow_left₀ h0 h1 45
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-268126187/5615859363936731136000000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm46 : (-517790116005838593419938448893619606250663/755578637259143234191360000000000000000000000000000000000000000000000000000000 : ℝ) ≤ (-620564861/101085468550861160448000000000 : ℝ) * θ ^ 46 := by
    have hp : θ ^ 46 ≤ (45/100:ℝ) ^ 46 := pow_le_pow_left₀ h0 h1 46
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-620564861/101085468550861160448000000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm47 : (-86027740965758426910151035194907039227321343/2417851639229258349412352000000000000000000000000000000000000000000000000000000000 : ℝ) ≤ (-309309456463/436689224139720213135360000000000 : ℝ) * θ ^ 47 := by
    have hp : θ ^ 47 ≤ (45/100:ℝ) ^ 47 := pow_le_pow_left₀ h0 h1 47
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-309309456463/436689224139720213135360000000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm48 : (-7959282365221834437926880416629336702350027/4835703278458516698824704000000000000000000000000000000000000000000000000000000000 : ℝ) ≤ (-117766649/1617367496813778567168000000000 : ℝ) * θ ^ 48 := by
    have hp : θ ^ 48 ≤ (45/100:ℝ) ^ 48 := pow_le_pow_left₀ h0 h1 48
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-117766649/1617367496813778567168000000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm49 : (-25559995350009201034927581011599882354943793/386856262276681335905976320000000000000000000000000000000000000000000000000000000000 : ℝ) ≤ (-3403703219/524027068967664255762432000000000 : ℝ) * θ ^ 49 := by
    have hp : θ ^ 49 ≤ (45/100:ℝ) ^ 49 := pow_le_pow_left₀ h0 h1 49
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-3403703219/524027068967664255762432000000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm50 : (-31558832874690770114017770602998838533094163/15474250491067253436239052800000000000000000000000000000000000000000000000000000000000 : ℝ) ≤ (-5764801/12938939974510228537344000000000 : ℝ) * θ ^ 50 := by
    have hp : θ ^ 50 ≤ (45/100:ℝ) ^ 50 := pow_le_pow_left₀ h0 h1 50
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-5764801/12938939974510228537344000000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm51 : (-24545758902537265644236043802332429970184349/618970019642690137449562112000000000000000000000000000000000000000000000000000000000000 : ℝ) ≤ (-40353607/2096108275870657023049728000000000 : ℝ) * θ ^ 51 := by
    have hp : θ ^ 51 ≤ (45/100:ℝ) ^ 51 := pow_le_pow_left₀ h0 h1 51
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-40353607/2096108275870657023049728000000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  have trm52 : (-171820312317760859509652306616327009791290443/495176015714152109959649689600000000000000000000000000000000000000000000000000000000000000 : ℝ) ≤ (-282475249/754598979313436528297902080000000000 : ℝ) * θ ^ 52 := by
    have hp : θ ^ 52 ≤ (45/100:ℝ) ^ 52 := pow_le_pow_left₀ h0 h1 52
    have := mul_le_mul_of_nonpos_left hp (by norm_num : (-282475249/754598979313436528297902080000000000 : ℝ) ≤ 0)
    norm_num at this ⊢
    linarith
  unfold Qpoly
  linarith [trm1, trm2, trm3, trm4, trm5, trm6, trm7, trm8, trm9, trm10, trm11, trm12, trm13, trm14, trm15, trm16, trm17, trm18, trm19, trm20, trm21, trm22, trm23, trm24, trm25, trm26, trm27, trm28, trm29, trm30, trm31, trm32, trm33, trm34, trm35, trm36, trm37, trm38, trm39, trm40, trm41, trm42, trm43, trm44, trm45, trm46, trm47, trm48, trm49, trm50, trm51, trm52]

/-! ## Taylor bounds for `sinh` and `cosh`

`Real.exp_bound` at `n = 6` gives `|e^x − Σ_{m<6} xᵐ/m!| ≤ 7|x|⁶/4320` for
`|x| ≤ 1`; averaging the bounds at `x` and `−x` gives the same remainder for
`sinh` and `cosh`. -/

theorem exp_taylor {x : ℝ} (hx : |x| ≤ 1) :
    |Real.exp x - (1 + x + x^2/2 + x^3/6 + x^4/24 + x^5/120)| ≤ 7 * |x|^6 / 4320 := by
  have h := Real.exp_bound hx (n := 6) (by norm_num)
  have hsum : ∑ m ∈ Finset.range 6, x ^ m / (Nat.factorial m)
      = 1 + x + x^2/2 + x^3/6 + x^4/24 + x^5/120 := by
    simp [Finset.sum_range_succ, Nat.factorial]
  rw [hsum] at h
  calc |Real.exp x - (1 + x + x^2/2 + x^3/6 + x^4/24 + x^5/120)|
      ≤ |x| ^ 6 * ((6:ℕ).succ / ((Nat.factorial 6) * 6 : ℝ)) := h
    _ = 7 * |x|^6 / 4320 := by norm_num [Nat.factorial]; ring

theorem sinh_taylor {θ : ℝ} (h0 : 0 ≤ θ) (h1 : θ ≤ 1) :
    |Real.sinh θ - (θ + θ^3/6 + θ^5/120)| ≤ 7 * θ^6 / 4320 := by
  have hx : |θ| ≤ 1 := by rw [abs_of_nonneg h0]; exact h1
  have hx' : |(-θ)| ≤ 1 := by rw [abs_neg]; exact hx
  have e1 := exp_taylor hx
  have e2 := exp_taylor hx'
  rw [abs_of_nonneg h0] at e1
  rw [abs_neg, abs_of_nonneg h0] at e2
  rw [Real.sinh_eq]
  have hstep : |(Real.exp θ - Real.exp (-θ))/2 - (θ + θ^3/6 + θ^5/120)|
      ≤ (|Real.exp θ - (1 + θ + θ^2/2 + θ^3/6 + θ^4/24 + θ^5/120)|
        + |Real.exp (-θ) - (1 + (-θ) + (-θ)^2/2 + (-θ)^3/6 + (-θ)^4/24 + (-θ)^5/120)|)/2 := by
    have : (Real.exp θ - Real.exp (-θ))/2 - (θ + θ^3/6 + θ^5/120)
        = ((Real.exp θ - (1 + θ + θ^2/2 + θ^3/6 + θ^4/24 + θ^5/120))
          - (Real.exp (-θ) - (1 + (-θ) + (-θ)^2/2 + (-θ)^3/6 + (-θ)^4/24 + (-θ)^5/120)))/2 := by
      ring
    rw [this, abs_div, abs_two]
    gcongr
    exact abs_sub _ _
  linarith

theorem cosh_taylor {θ : ℝ} (h0 : 0 ≤ θ) (h1 : θ ≤ 1) :
    |Real.cosh θ - (1 + θ^2/2 + θ^4/24)| ≤ 7 * θ^6 / 4320 := by
  have hx : |θ| ≤ 1 := by rw [abs_of_nonneg h0]; exact h1
  have hx' : |(-θ)| ≤ 1 := by rw [abs_neg]; exact hx
  have e1 := exp_taylor hx
  have e2 := exp_taylor hx'
  rw [abs_of_nonneg h0] at e1
  rw [abs_neg, abs_of_nonneg h0] at e2
  rw [Real.cosh_eq]
  have hstep : |(Real.exp θ + Real.exp (-θ))/2 - (1 + θ^2/2 + θ^4/24)|
      ≤ (|Real.exp θ - (1 + θ + θ^2/2 + θ^3/6 + θ^4/24 + θ^5/120)|
        + |Real.exp (-θ) - (1 + (-θ) + (-θ)^2/2 + (-θ)^3/6 + (-θ)^4/24 + (-θ)^5/120)|)/2 := by
    have : (Real.exp θ + Real.exp (-θ))/2 - (1 + θ^2/2 + θ^4/24)
        = ((Real.exp θ - (1 + θ + θ^2/2 + θ^3/6 + θ^4/24 + θ^5/120))
          + (Real.exp (-θ) - (1 + (-θ) + (-θ)^2/2 + (-θ)^3/6 + (-θ)^4/24 + (-θ)^5/120)))/2 := by
      ring
    rw [this, abs_div, abs_two]
    gcongr
    exact abs_add_le _ _
  linarith

/-! ## Assembling regime 1 -/

/-- `cosh 2θ = 1 + 2 sinh²θ`. -/
theorem cosh_two_mul' (θ : ℝ) : Real.cosh (2 * θ) = 1 + 2 * Real.sinh θ ^ 2 := by
  rw [Real.cosh_two_mul, Real.cosh_sq']
  ring

/-- The algebraic core of regime 1, in the variables `a = θ cosh θ`, `s = sinh θ`. -/
theorem alg_ineq {θ : ℝ} (h0 : 0 < θ) (h1 : θ ≤ 45/100) :
    3 * Real.sinh θ * (θ * Real.cosh θ + Real.sinh θ ^ 3) ^ 3
      < 3 * (θ * Real.cosh θ) ^ 2 * (θ * Real.cosh θ + Real.sinh θ ^ 3) ^ 2
        + 2 * (θ * Real.cosh θ) ^ 3 * Real.sinh θ ^ 2
            * (θ * Real.cosh θ + Real.sinh θ ^ 3)
        + (θ * Real.cosh θ) ^ 4 * Real.sinh θ ^ 4 := by
  have hθ1 : θ ≤ 1 := by linarith
  have hθ0 : (0:ℝ) ≤ θ := le_of_lt h0
  -- Taylor enclosures
  have hs := abs_le.mp (sinh_taylor hθ0 hθ1)
  have hc := abs_le.mp (cosh_taylor hθ0 hθ1)
  set s := Real.sinh θ with hsdef
  set c := Real.cosh θ with hcdef
  set E : ℝ := 7 * θ ^ 6 / 4320 with hEdef
  have hslo : θ + θ^3/6 + θ^5/120 - E ≤ s := by linarith [hs.1]
  have hshi : s ≤ θ + θ^3/6 + θ^5/120 + E := by linarith [hs.2]
  have hclo : 1 + θ^2/2 + θ^4/24 - E ≤ c := by linarith [hc.1]
  have hchi : c ≤ 1 + θ^2/2 + θ^4/24 + E := by linarith [hc.2]
  have hEpos : 0 ≤ E := by positivity
  have hspos : 0 < s := Real.sinh_pos_iff.mpr h0
  have hcpos : 0 < c := Real.cosh_pos θ
  -- the two envelopes are positive
  have hslopos : 0 < θ + θ^3/6 + θ^5/120 - E := by
    have : E ≤ 7 * θ / 4320 * θ^5 := by rw [hEdef]; ring_nf; nlinarith [pow_pos h0 5]
    nlinarith [pow_pos h0 3, pow_pos h0 5, pow_pos h0 6]
  have hclopos : 0 < 1 + θ^2/2 + θ^4/24 - E := by
    have h6 : θ^6 ≤ 45/100 * θ^5 := by nlinarith [pow_pos h0 5]
    have h5 : θ^5 ≤ 45/100 * θ^4 := by nlinarith [pow_pos h0 4]
    have h4 : θ^4 ≤ 45/100 * θ^3 := by nlinarith [pow_pos h0 3]
    have h3 : θ^3 ≤ 45/100 * θ^2 := by nlinarith [pow_pos h0 2]
    have h2 : θ^2 ≤ 45/100 * θ := by nlinarith
    nlinarith [pow_pos h0 2, sq_nonneg θ]
  -- monotone substitution into both sides
  have hLmono : 3 * s * (θ * c + s ^ 3) ^ 3
      ≤ 3 * (θ + θ^3/6 + θ^5/120 + E)
        * (θ * (1 + θ^2/2 + θ^4/24 + E) + (θ + θ^3/6 + θ^5/120 + E) ^ 3) ^ 3 := by
    gcongr <;> first
      | exact hshi | exact hchi | positivity | linarith
  have hRmono : 3 * (θ * (1 + θ^2/2 + θ^4/24 - E)) ^ 2
        * (θ * (1 + θ^2/2 + θ^4/24 - E) + (θ + θ^3/6 + θ^5/120 - E) ^ 3) ^ 2
      + 2 * (θ * (1 + θ^2/2 + θ^4/24 - E)) ^ 3 * (θ + θ^3/6 + θ^5/120 - E) ^ 2
          * (θ * (1 + θ^2/2 + θ^4/24 - E) + (θ + θ^3/6 + θ^5/120 - E) ^ 3)
      + (θ * (1 + θ^2/2 + θ^4/24 - E)) ^ 4 * (θ + θ^3/6 + θ^5/120 - E) ^ 4
      ≤ 3 * (θ * c) ^ 2 * (θ * c + s ^ 3) ^ 2
        + 2 * (θ * c) ^ 3 * s ^ 2 * (θ * c + s ^ 3)
        + (θ * c) ^ 4 * s ^ 4 := by
    gcongr <;> first
      | exact hclo | exact hslo | positivity | linarith
  -- the polynomial gap is `θ⁸ · Qpoly θ`
  have hpoly : 3 * (θ + θ^3/6 + θ^5/120 + E)
        * (θ * (1 + θ^2/2 + θ^4/24 + E) + (θ + θ^3/6 + θ^5/120 + E) ^ 3) ^ 3
      < 3 * (θ * (1 + θ^2/2 + θ^4/24 - E)) ^ 2
          * (θ * (1 + θ^2/2 + θ^4/24 - E) + (θ + θ^3/6 + θ^5/120 - E) ^ 3) ^ 2
        + 2 * (θ * (1 + θ^2/2 + θ^4/24 - E)) ^ 3 * (θ + θ^3/6 + θ^5/120 - E) ^ 2
            * (θ * (1 + θ^2/2 + θ^4/24 - E) + (θ + θ^3/6 + θ^5/120 - E) ^ 3)
        + (θ * (1 + θ^2/2 + θ^4/24 - E)) ^ 4 * (θ + θ^3/6 + θ^5/120 - E) ^ 4 := by
    have hid : (3 * (θ * (1 + θ^2/2 + θ^4/24 - E)) ^ 2
          * (θ * (1 + θ^2/2 + θ^4/24 - E) + (θ + θ^3/6 + θ^5/120 - E) ^ 3) ^ 2
        + 2 * (θ * (1 + θ^2/2 + θ^4/24 - E)) ^ 3 * (θ + θ^3/6 + θ^5/120 - E) ^ 2
            * (θ * (1 + θ^2/2 + θ^4/24 - E) + (θ + θ^3/6 + θ^5/120 - E) ^ 3)
        + (θ * (1 + θ^2/2 + θ^4/24 - E)) ^ 4 * (θ + θ^3/6 + θ^5/120 - E) ^ 4)
        - 3 * (θ + θ^3/6 + θ^5/120 + E)
          * (θ * (1 + θ^2/2 + θ^4/24 + E) + (θ + θ^3/6 + θ^5/120 + E) ^ 3) ^ 3
        = θ ^ 8 * Qpoly θ := by
      rw [hEdef, Qpoly]
      ring
    have hq := Qpoly_pos hθ0 h1
    have h8 : (0:ℝ) < θ ^ 8 := pow_pos h0 8
    linarith [hid, mul_pos h8 hq]
  linarith

/-- **Regime 1 of (iii)'s core**: `F > 0` on `(0, 0.45]`. -/
theorem core_pos_regime1 {θ : ℝ} (h0 : 0 < θ) (h1 : θ ≤ 45/100) : 0 < F θ := by
  refine F_pos_of_exp_bound h0 ?_
  have hspos : 0 < Real.sinh θ := Real.sinh_pos_iff.mpr h0
  have hcpos : 0 < Real.cosh θ := Real.cosh_pos θ
  set s := Real.sinh θ with hsdef
  set c := Real.cosh θ with hcdef
  have hD : 0 < θ * c + s ^ 3 := by positivity
  have hZ : Real.cosh (2 * θ) = 1 + 2 * s ^ 2 := cosh_two_mul' θ
  -- `y = 2(θc)s²/(θc + s³)`
  have hy : yOf θ = 2 * (θ * c) * s ^ 2 / (θ * c + s ^ 3) := by
    have hW : W θ = 2 * (θ * c + s ^ 3) / c := by
      simp only [W, Real.tanh_eq_sinh_div_cosh, hZ, ← hsdef, ← hcdef]
      field_simp
      ring
    simp only [yOf, hW, hZ]
    field_simp
    ring
  rw [hZ, hy]
  -- the gap equals `16 s⁴ · (alg gap) / (24 D⁴)`
  have key := alg_ineq h0 h1
  set A := θ * c with hAdef
  set D := θ * c + s ^ 3 with hDdef
  have hid : 2 * A * s ^ 2 / D + (2 * A * s ^ 2 / D) ^ 2 / 2
        + (2 * A * s ^ 2 / D) ^ 3 / 6 + (2 * A * s ^ 2 / D) ^ 4 / 24 - 2 * s ^ 2
      = 16 * s ^ 4 * ((3 * A ^ 2 * D ^ 2 + 2 * A ^ 3 * s ^ 2 * D + A ^ 4 * s ^ 4)
          - 3 * s * D ^ 3) / (24 * D ^ 4) := by
    field_simp
    ring
  have hgap : 0 < 16 * s ^ 4 * ((3 * A ^ 2 * D ^ 2 + 2 * A ^ 3 * s ^ 2 * D + A ^ 4 * s ^ 4)
      - 3 * s * D ^ 3) / (24 * D ^ 4) := by
    apply div_pos _ (by positivity)
    have h1' : 0 < (3 * A ^ 2 * D ^ 2 + 2 * A ^ 3 * s ^ 2 * D + A ^ 4 * s ^ 4)
        - 3 * s * D ^ 3 := by
      simp only [hAdef, hDdef]
      linarith [key]
    positivity
  linarith [hid ▸ hgap]

end BSCAveraging.Core
